"""Cria a tabela de mentores

Revision ID: c2f4dca5265f
Revises: 
Create Date: 2025-08-26 18:37:15.160986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f4dca5265f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('experience_of_years', sa.Integer(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentors_email'), 'mentors', ['email'], unique=True)
    op.create_index(op.f('ix_mentors_id'), 'mentors', ['id'], unique=False)
    op.create_index(op.f('ix_mentors_location'), 'mentors', ['location'], unique=False)
    op.create_index(op.f('ix_mentors_name'), 'mentors', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentors_name'), table_name='mentors')
    op.drop_index(op.f('ix_mentors_location'), table_name='mentors')
    op.drop_index(op.f('ix_mentors_id'), table_name='mentors')
    op.drop_index(op.f('ix_mentors_email'), table_name='mentors')
    op.drop_table('mentors')
    # ### end Alembic commands ###
